name: pr

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node: ['20.19.0', '22.12.0', '24.0.0']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Prettier
        run: npm run prettier:check
      - name: Run knip
        run: npx knip
      - name: Typecheck
        run: npm run typecheck
      - name: Build & Test
        run: npm run test:ci
